# Generated by Django 6.0.6 on 2026-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='workspace_channel_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
