# Generated by Django 6.0.6 on 2026-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_workspace_channel_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
