# Generated by Django 6.0.6 on 2026-09-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_schedule_date_alter_post_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_medias', to='posts.post'),
        ),
    ]
