# Generated by Django 6.0.6 on 2026-09-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postmedia_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
