# Generated by Django 6.0.6 on 2026-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postmedia_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='post',
            name='schedule_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
