# Generated by Django 6.0.6 on 2026-09-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('partial', 'Partial'), ('pending', 'Pending'), ('process_failed', 'Process Failed'), ('for_approval', 'For Approval'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
