# Generated by Django 6.0.6 on 2026-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_request_to',
            field=models.CharField(blank=True, choices=[('schedule', 'Schedule'), ('"my_time"', '"My Time"')], max_length=50, null=True),
        ),
    ]
