# Generated by Django 6.0.6 on 2026-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_post_request_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='public_id',
            field=models.CharField(max_length=250, default='my-id'),
        ),
    ]
