# Generated by Django 6.0.6 on 2026-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postmedia_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='public_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
