# Generated by Django 6.0.6 on 2026-10-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_postmedia_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='public_id',
        ),
    ]
