# Generated by Django 6.0.6 on 2026-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_postmedia_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='public_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
