# Generated by Django 6.0.6 on 2026-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('team', 'Team')], max_length=20),
        ),
    ]
