# Generated by Django 6.0.6 on 2026-08-25 09:56

from django.db import migrations


def add_permissions(apps, schema_editor):
    # apps.get_model() — gets model without importing directly
    # why? because migrations use historical model versions
    Permission = apps.get_model("workspaces", "Permission")

    permissions = [
        "workspace:can_update",
        "workspace:can_delete",
        "workspace:can_invite_members",
        "workspace:can_delete_members",
        "workspace:can_create_roles",
        "workspace:can_update_roles",
        "workspace:can_delete_roles",
        "channels:can_connect",
        "channels:can_disconnect",
        "post:can_create",
        "post:can_publish",
        "post:can_request_approval",
        "post:can_approve",
        "post:can_update",
        "post:can_delete",
        "post:can_view_detail",
        "idea:can_create",
        "idea:can_delete",
        "idea:can_view_detail",
        "idea:can_update",
        "template:can_create",
        "template:can_update",
        "template:can_delete",
        "template:can_view_detail",
        "my_time:can_create",
        "my_time:can_update",
        "my_time:can_delete",
        "analytics:can_view",
        "comments:can_view",
        "comments:can_reply",
    ]

    for permission in permissions:
        Permission.objects.create(title=permission)


class Migration(migrations.Migration):
    dependencies = [
        ('workspaces', '0002_alter_workspace_type'),
    ]
    
    operations = [migrations.RunPython(add_permissions)]
