# Generated by Django 6.0.6 on 2026-06-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_backup_email_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
