# Generated by Django 6.0.6 on 2026-08-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_max_channels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='last_used_at',
            new_name='last_active_at',
        ),
    ]
