# Generated by Django 6.0.6 on 2026-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_last_used_at_usertoken_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
