# Generated by Django 6.0.6 on 2026-08-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50)),
                ('max_channels', models.IntegerField()),
                ('queue_limit', models.IntegerField()),
                ('allow_analytics', models.BooleanField(default=False)),
                ('allow_team', models.BooleanField(default=False)),
                ('template_type', models.CharField(choices=[('basic', 'Basic'), ('full', 'Full')], max_length=50)),
                ('comment_and_reply', models.BooleanField(default=False)),
                ('activity_log', models.BooleanField(default=False)),
                ('custom_time_slots', models.BooleanField(default=False)),
                ('ai_generative_caption', models.BooleanField(default=False)),
                ('max_ai_generative_caption', models.IntegerField(default=0)),
                ('ai_generative_hastags', models.BooleanField(default=False)),
                ('max_ai_generative_hastags', models.IntegerField(default=0)),
                ('ai_generative_ideas', models.BooleanField(default=False)),
                ('max_ai_generative_ideas', models.IntegerField(default=0)),
                ('max_workspaces', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
