# Generated by Django 6.0.6 on 2026-09-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_workspaces',
            field=models.IntegerField(default=1),
        ),
    ]
