# Generated by Django 6.0.6 on 2026-09-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
