# Generated by Django 6.0.6 on 2026-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='is_deleted',
        ),
    ]
