# Generated by Django 6.0.6 on 2026-09-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_remove_channel_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug_url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
