# Generated by Django 6.0.6 on 2026-09-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_channel_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug_url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
