# Generated by Django 6.0.6 on 2026-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_alter_channel_slug_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacechannel',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
