# Generated by Django 6.0.6 on 2026-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_workspacechannel_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacechannel',
            name='email',
        ),
        migrations.AddField(
            model_name='workspacechannel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
