# Generated by Django 6.0.6 on 2026-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_workspacechannel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacechannel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
