# Generated by Django 6.0.6 on 2026-09-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_alter_workspacechannel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacechannel',
            name='profile_picture',
            field=models.CharField(blank=True, null=True),
        ),
    ]
