# Generated by Django 6.0.6 on 2026-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_alter_workspacechannel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacechannel',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
