# Generated by Django 6.0.6 on 2026-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_alter_workspacechannel_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacechannel',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
