# Generated by Django 6.0.6 on 2026-09-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_workspacechannel_page_id_workspacechannel_page_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacechannel',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='workspacechannel',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='workspacechannel',
            name='page_name',
        ),
    ]
