# Generated by Django 6.0.6 on 2026-09-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0015_rename_full_name_workspacechannel_name_and_more'),
        ('posts', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_posts', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='workspace_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_channel_posts', to='channels.workspacechannel'),
        ),
    ]
